#*******************************************************************************
#.appveyor.yml
#*******************************************************************************

#Purpose:
#AppVeyor is a hosted continuous integration service, that is, it allows running
#code directly from a repository and checking that the code acts as expected. 
#The purpose of the .appveyor.yml file is to give instructions to AppVeyor on
#how to do the work.
#Author:
#Cedric H. David, 2018-2018


#*******************************************************************************
#System specifications for AppVeyor
#*******************************************************************************
version: 1.0.{build}

build: false

image:
  - Visual Studio 2015
  

#*******************************************************************************
#Environment variables for different tests on multiple AppVeyor workers
#*******************************************************************************
environment:
  ci_user_password:
    secure: tm75eKllwolkg4o/C+8w5A==
  matrix:
    - TST_PUB_DWNL: 'tst_pub_dwnl_David_etal_201x_SER.sh'
      TST_PUB_REPR: 'tst_pub_repr_David_etal_201x_SER.sh'


#*******************************************************************************
#Before installing SHBAAM
#*******************************************************************************
install:
  - ps: rm Alias:wget
  - ps: choco install --no-progress ((gc requirements.cho) -notmatch '^#' -match '\S')
  - ps: $ENV:PATH="C:\\ProgramData\\MiniConda2;C:\\ProgramData\\MiniConda2\\Scripts;$ENV:PATH"
  - ps: $ENV:PATH="C:\\Program Files (x86)\\GnuWin32\\bin;$ENV:PATH"
  - ps: set-content ~/.netrc "machine urs.earthdata.nasa.gov login salichao@uci.edu password $env:ci_user_password"
  - ps: cp ~/.netrc ~/_netrc
#*******************************************************************************
#Installing SHBAAM
#*******************************************************************************
build_script:
  - ps: conda install -y -q -c anaconda --file requirements.cnd


#*******************************************************************************
#Testing SHBAAM
#*******************************************************************************
test_script:
  - ps: cd tst
  - ps: Write-Host $env:TST_PUB_DWNL
  - ps: bash $env:TST_PUB_DWNL
  - ps: Write-Host $env:TST_PUB_REPR
  - ps: bash $env:TST_PUB_REPR


#*******************************************************************************
#End
#*******************************************************************************
